package FinallyThrow;

public class Throw {
    /*
        Throw: É a assiantura do método que será retornado caso ocorra erro para o método que fez a chamada, dentro de um fluxo encadeado
        Throws: É usado para lnaçar a exceção desejada, juntamente com a mensagem de erro, para o método que fez a chamada

    public String recuperarIdUsuario (String query) throws AcessoADaadosException {
        try {
            PreparedStatement stmt = con.prepareStatement(query);
            //...
        } catch (SQLException e){
            throw new AcessoADadosException("Problema na criação de Statement", e);
        }

    }*/
}
